export enum TicketErrorMessages {
  TITLE_INVALID = "TITLE_INVALID",
  TITLE_REQUIRED = "TITLE_REQUIRED",
  PRICE_INVALID = "PRICE_INVALID",
  PRICE_REQUIRED = "PRICE_REQUIRED",
  ID_INVALID = "ID_INVALID",
}
