export enum ErrorMessages {
  EMAIL_REQUIRED = "EMAIL_REQUIRED",
  EMAIL_INVALID = "EMAIL_INVALID",
  PASSWORD_REQUIRED = "PASSWORD_REQUIRED",
  PASSWORD_INVALID = "PASSWORD_INVALID",
  PASSWORD_TO_WEAK = "PASSWORD_TO_WEAK",
  USER_NOT_FOUND = "USER_NOT_FOUND",
}
